### ISSUE TITLE
Warning about "spec.template.spec.containers[0].ports[0].targetPort"

### ISSUE THREAD

**Issue by baskinsy** [f3k-tech/helm#1]
Hello,

There is a no fatal warning (deployment works) and I can access the web interface.

```
W1111 15:34:15.446954   25709 warnings.go:70] unknown field "spec.template.spec.containers[0].ports[0].targetPort"
```

Running on kubernetes v1.25.13 with helm v3.13.1

**Comment by f3k-freek** [comment]
Thank you very much for pointing this out. It's fixed in 0.1.7. I've also pushed 0.1.8 with updated container.
