### ISSUE TITLE
[Question] Is perstistence working as it is with autoscaling enabled?

### ISSUE THREAD

**Issue by baskinsy** [f3k-tech/helm#2]
Just a question to clarify how the persistence of volumes will work with autoscaling enabled. 

I am using autoscaling without persistence for now and it works as expected although every time new pods are launched (due to autoscaling) they need to download the language data (it takes around 1 min on my setup but it would be good to be spontaneous by accessing the persistent data from the first pod).  

should the volumes be "ReadWriteMany" for the autoscaling to work or the "ReadWriteOnce" is enough?

Thank you in advance.

**Comment by f3k-freek** [comment]
My  storage provisioner  doesn't support RWX, so I haven't been able to test that. I just tested RWO and that doesn't work since the init containers of the replica's don't have write access.

I'll try to fix it in a future update. But I don't have any indication when I'll have time for that. If your storage provisioner supports RWX, then that might work. I would suggest to only persist the share and db folders at first.

**Comment by baskinsy** [comment]
Got it, I'll check how it behaves and report back. I use Longhorn on my cluster as storage engine and support RWX volumes.

**Comment by f3k-freek** [comment]
I have tested it with Longhorn and it seems to work fine in RWX mode with multiple replicas.
- I persisted all three volumes in ReadWriteMany accesMode.
- Enabled autoscaling
- set autoscaling.Replicas to 10 (replicaCount is ignored when autoscaling is enabled)

> **NB:** After the translation files were downloaded from multiple replica's, only two languages showed up in the web interface. After running a single replica with the ```--update-models``` argument, all languages showed up. After that I added more replica's and the languages still showed up fine.

**Comment by baskinsy** [comment]
I deployed without issues. With persistent RWX volumes and autoscaling enabled. Didn't have an issue with languages, because only one replica was deployed. Will also test the autoscaling and report back but seems ok.

**Comment by f3k-freek** [comment]
Great to hear and thank you for helping with testing and reporting back!
