### ISSUE TITLE
[libretranslate] Add /tmp volume to support file translation when using multiple replicas

### ISSUE THREAD

**Issue by cyrinux** [f3k-tech/helm#3]
Hi,
It turn out translated file are store by default in `/tmp` so, If the session affinity is not good we have to refresh several time and by chance we can get from the pod that did the translation.
Can you try to fix this by making this using a share pvc ?

**Comment by amaze-escape** [comment]
Done! The volume is added in 1.0.7. Thank you for pointing this out. I've tested it with ten pods and I could download the  same file after refreshing every time. Could you report back if it indeed fixed your issue?

**Comment by f3k-freek** [comment]
Done! The volume is added in 1.0.7. Thank you for pointing this out. I've tested it with ten pods and I could download the same file after refreshing every time. Could you report back if it indeed fixed your issue?

**Comment by cyrinux** [comment]
Hello !

In theory its better like this, but after, with my last try I got a 500 I have to refresh one time.
It depends of the CSI you use I think.

Also,  I realize there is a subdirectory, It would be better to just map this one `/tmp/libretranslate-files-translate`. 😃 

Log example:

```
libretranslate-6776dcf6c-mcnj9 libretranslate FileNotFoundError: [Errno 2] No such file or directory: '/tmp/libretranslate-files-translate/19a8a48a-1ec8-46f7-b11e-69811a67d3f3.README_fr.txt'
```

Thanks you !

**Comment by f3k-freek** [comment]
Why would it be better to just mount the ```/tmp/libretranslate-files-translate```? Maybe we should ask the developer of libretranslate which directories should have a shared volume. I can think of reasons in favour of and against sharing the entire tmp folder.

**Comment by f3k-freek** [comment]
> In theory its better like this, but after, with my last try I got a 500 I have to refresh one time.

@cyrinux Could you elaborate on this? Do you have to refresh every time you visit the page? Does it only apply to the translate files process?

**Comment by cyrinux** [comment]
> Why would it be better to just mount the `/tmp/libretranslate-files-translate`? Maybe we should ask the developer of libretranslate which directories should have a shared volume. I can think of reasons in favour of and against sharing the entire tmp folder.

Because just in general in /tmp a lot of different thing can be put here, I think its better if we know the real full path to target it.
If something else is store in /tmp for processing of the data and if I use a slow CSI (aka remote storage), not local, this can slow a lot the processing.

**Comment by cyrinux** [comment]
> > In theory its better like this, but after, with my last try I got a 500 I have to refresh one time.
> 
> @cyrinux Could you elaborate on this? Do you have to refresh every time you visit the page? Does it only apply to the translate files process?

I was not yet able to do a lot of test, I will retry, but i'm pretty sure after the /tmp share in place, its a matter of syncing/flushing the data on my remote path the issue. Still, I also have to find way to configure my ingress to keep/pin the client connection on the same pod and not start the flow on one pod and then get move on another. This is a setup issue on my side then I suppose.

**Comment by f3k-freek** [comment]
From the k8s docs: 
_If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting ```.spec.sessionAffinity``` to ```ClientIP``` for a Service (the default is None)._
Source:  https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity

I've tried it and it didn't fix the issue for me. If it does, I will definitely add this to the helm chart.

This is how I tried altered the service to make it sticky (which didn't help):

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: libretranslate
    meta.helm.sh/release-namespace: libretranslate
  creationTimestamp: "<creation-date>"
  labels:
    app.kubernetes.io/instance: libretranslate
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: libretranslate
    app.kubernetes.io/version: "<app-version>"
    helm.sh/chart: libretranslate-<chart-version>
  name: libretranslate
  namespace: libretranslate
  resourceVersion: "<resource-version>"
  uid: "<uid>"
spec:
  clusterIP: <cluster-IP>
  clusterIPs:
  - <cluster-IP>
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: libretranslate
    app.kubernetes.io/name: libretranslate
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
 ```

**Comment by cyrinux** [comment]
Thank, I will try with traefik, what ingress controller are you using?

**Comment by cyrinux** [comment]
* With traefik, looks like adding this works, so we just need to be able to add custom annotations to the ingress.

```  
  traefik.ingress.kubernetes.io/affinity: "true"
  traefik.ingress.kubernetes.io/session-cookie-name: "sticky-session-cookie-name"
```
~Can you support annotations for the ingress if its not already the case ? I just edit manually for my tests.~
We already can add annotations for the ingress, cool !

About my tmp volume, its well a sync problem as I use s3, so better to well stick the client with those annotations.

* About volumes, I try mapping /tmp/libretranslate-files-translate  instead of whole /tmp and it still works as expected

**Comment by f3k-freek** [comment]
Thank you for figuring this out! I will add it to the readme.
I will think about what to do with the /tmp and /tmp/libretranslate-files-translate directories.

**Comment by cyrinux** [comment]
https://github.com/f3k-tech/helm/pull/5
